// FETCH RESTAURANTS
export const FETCH_RESTAURANT_DATA__REQUEST = 'FETCH_RESTAURANT_DATA__REQUEST';
export const FETCH_RESTAURANT_DATA__FAILURE = 'FETCH_RESTAURANT_DATA__FAILURE';
export const FETCH_RESTAURANT_DATA__SUCCESS = 'FETCH_RESTAURANT_DATA__SUCCESS';
