export const states = [
{label: "All", abbr: "ALL"},
{label: "Alabama", abbr: "AL"},
{label: "Alaska", abbr: "AK"},
{label: "Arizona", abbr: "AZ"},
{label: "Arkansas", abbr: "AR"},
{label: "California", abbr: "CA"},
{label: "Colorado", abbr: "CO"},
{label: "Connecticut", abbr: "CT"},
{label: "Delaware", abbr: "DE"},
{label: "Florida", abbr: "FL"},
{label: "Georgia", abbr: "GE"},
{label: "Hawaii", abbr: "HI"},
{label: "Idaho", abbr: "ID"},
{label: "Illinois", abbr: "IL"},
{label: "Indiana", abbr: "AN"},
{label: "Iowa", abbr: "IA"},
{label: "Kansas", abbr: "KS"},
{label: "Kentucky", abbr: "KY"},
{label: "Louisiana", abbr: "LA"},
{label: "Maine", abbr: "ME"},
{label: "Maryland", abbr: "MD"},
{label: "Massachusetts", abbr: "MA"},
{label: "Michigan", abbr: "MI"},
{label: "Minnesota", abbr: "MN"},
{label: "Mississippi", abbr: "MS"},
{label: "Missouri", abbr: "MO"},
{label: "Montana", abbr: "MT"},
{label: "Nebraska", abbr: "NE"},
{label: "Nevada", abbr: "NV"},
{label: "New Hampshire", abbr: "NH"},
{label: "New Jersey", abbr: "NJ"},
{label: "New Mexico", abbr: "NM"},
{label: "New York", abbr: "NY"},
{label: "North Carolina", abbr: "NC"},
{label: "North Dakota", abbr: "ND"},
{label: "Ohio", abbr: "OH"},
{label: "Oklahoma", abbr: "OK"},
{label: "Oregon", abbr: "OR"},
{label: "Pennsylvania", abbr: "PA"},
{label: "Rhode Island", abbr: "RI"},
{label: "South Carolina", abbr: "SC"},
{label: "South Dakota", abbr: "SD"},
{label: "Tennessee", abbr: "TN"},
{label: "Texas", abbr: "TX"},
{label: "Utah", abbr: "UT"},
{label: "Vermont", abbr: "VT"},
{label: "Virginia", abbr: "VA"},
{label: "Washington", abbr: "WA"},
{label: "West Virginia", abbr: "WV"},
{label: "Wisconsin", abbr: "WI"},
{label: "Wyoming", abbr: "WY"}
];
